name: 'Setup Build Environment'
description: 'Setup Python, Rust, and build tools with caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  install-cargo-tools:
    description: 'Whether to install cargo tools'
    required: false
    default: 'true'
  install-python-deps:
    description: 'Whether to install Python build dependencies'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        rustflags: ""

    - name: Add Rust Targets
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          rustup target add wasm32-unknown-unknown x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
        elif [ "${{ runner.os }}" == "macOS" ]; then
          rustup target add wasm32-unknown-unknown x86_64-apple-darwin aarch64-apple-darwin
        fi

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Zig toolchain
      uses: mlugg/setup-zig@v2

    - name: Install system build tools (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/zig
        # Cache key includes:
        # - OS: different OSes have different binaries
        # - action.yml hash: invalidates cache when action changes
        # - Python version: different Python versions may need different tools
        # - Rust toolchain: nightly toolchain version
        # - Tool versions: dioxus-cli version (update when tool versions change)
        # - Cargo.lock: invalidates when dependencies change
        key: ${{ runner.os }}-setup-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}-python-${{ inputs.python-version }}-rust-nightly-dx-0.7.2-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-setup-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}-python-${{ inputs.python-version }}-rust-nightly-dx-0.7.2-cargo-
          ${{ runner.os }}-setup-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}-cargo-
          ${{ runner.os }}-cargo-

    - name: Install cargo tools
      if: inputs.install-cargo-tools == 'true'
      shell: bash
      run: |
        test -e ~/.cargo/bin/cargo-zigbuild || cargo install cargo-zigbuild
        test -e ~/.cargo/bin/rnr || cargo install rnr
        test -e ~/.cargo/bin/cargo-nextest || cargo install cargo-nextest
        test -e ~/.cargo/bin/dx || cargo install dioxus-cli@0.7.2

    - name: Install Python Build Dependencies
      if: inputs.install-python-deps == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build wheel toml maturin
